--------------------------------------------------------
--  File created - Friday-August-28-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TWITTER_USER
--------------------------------------------------------

  CREATE TABLE "TESTDB"."TWITTER_USER" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TESTDB.TWITTER_USER
SET DEFINE OFF;
Insert into TESTDB.TWITTER_USER (ID,NAME,PASSWORD) values ('1','him','him');
--------------------------------------------------------
--  DDL for Index TWITTER_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."TWITTER_USER_PK" ON "TESTDB"."TWITTER_USER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TWITTER_USER
--------------------------------------------------------

  ALTER TABLE "TESTDB"."TWITTER_USER" ADD CONSTRAINT "TWITTER_USER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."TWITTER_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "TESTDB"."TWITTER_USER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TESTDB"."TWITTER_USER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger TWITTER_USER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."TWITTER_USER_TRG" 
BEFORE INSERT ON TWITTER_USER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TWITTER_USER_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."TWITTER_USER_TRG" ENABLE;
